# Generated by Django 4.2 on 2023-12-25 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('Total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recieve_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Card_Number', models.CharField(blank=True, max_length=16, null=True)),
                ('CVV', models.CharField(blank=True, max_length=4, null=True)),
                ('Card_password', models.CharField(blank=True, max_length=20, null=True)),
                ('Exp_Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Adress', models.CharField(blank=True, max_length=50, null=True)),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('carreir', models.CharField(blank=True, max_length=10, null=True)),
                ('Payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Cart.order')),
            ],
        ),
    ]
