# Generated by Django 4.2 on 2024-01-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_cart_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
